auth:
  type: ${AUTH_TYPE:DISABLED}
  oauth2:
    client:
      google:
        provider: google
        clientId: ${GOOGLE_CLIENT_ID:}
        clientSecret: ${GOOGLE_CLIENT_SECRET:}
        clientName: Google
        redirectUri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
        authorizationGrantType: authorization_code
        scope:
          - openid
          - profile
          - email
        authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
        tokenUri: https://oauth2.googleapis.com/token
        userInfoUri: https://openidconnect.googleapis.com/v1/userinfo
        jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
        userNameAttribute: email
        customParams:
          type: google

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

springdoc:
  path: /swagger
  api-docs:
    enabled: ${SWAGGER_UI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}
    url: /openapi/kafbat-ui-api.yaml
    urls:
      - name: kafbat-ui
        url: /openapi/kafbat-ui-api.yaml
    config-url: null
  override-with-generic-response: true

logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.hibernate.validator: WARN

